branches:
  - release/core
language: csharp
solution: Nintek.Core.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
  - dotnet pack --configuration Release Nintek.Core
deploy:
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push Nintek.Core/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://www.nuget.org/api/v2/package
    on:
      branch: release/core
