branches:
  - release/core
  - release/domain
  - release/domain-common
  - release/events
  - release/data
language: csharp
solution: Nintek.Core.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
  - if [ "$TRAVIS_BRANCH" = "release/core" ]; then dotnet pack --configuration Release Nintek.Core; fi
  - if [ "$TRAVIS_BRANCH" = "release/domain" ]; then dotnet pack --configuration Release Nintek.Core.Domain; fi
  - if [ "$TRAVIS_BRANCH" = "release/domain-common" ]; then dotnet pack --configuration Release Nintek.Core.Domain.Common; fi
  - if [ "$TRAVIS_BRANCH" = "release/events" ]; then dotnet pack --configuration Release Nintek.Core.Events; fi
  - if [ "$TRAVIS_BRANCH" = "release/data" ]; then dotnet pack --configuration Release Nintek.Core.Data; fi
deploy:
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push Nintek.Core/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://www.nuget.org/api/v2/package
    on:
      branch: release/core
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push Nintek.Core.Domain/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://www.nuget.org/api/v2/package
    on:
      branch: release/domain
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push Nintek.Core.Domain.Common/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://www.nuget.org/api/v2/package
    on:
      branch: release/domain-common
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push Nintek.Core.Events/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://www.nuget.org/api/v2/package
    on:
      branch: release/events
